### ISSUE TITLE
Criticas construtivas

### ISSUE THREAD

**Issue by JhoanDev** [classroom-ufersa/GerenciamentoDeBiblioteca#1]
## Feedback sobre o código em C na branch main

~~1. **Warnings ao compilar:** Foram observados vários warnings durante a compilação do código. É importante resolver esses warnings, pois podem indicar possíveis problemas no código que podem afetar seu funcionamento.~~

~~2. **Quebra ao digitar letras no menu:** Ao digitar letras no menu, o código quebra. Isso pode ser frustrante para o usuário e deve ser corrigido para garantir uma experiência de uso melhor.~~

~~4. **Utilização de apenas um arquivo .txt:** A sugestão é utilizar apenas um arquivo .txt em vez de dois para armazenar os dados.~~

~~5. **Estrutura da main:** Na main, deve existir apenas a lista de usuários, enquanto as listas de livros devem estar dentro de cada nó da lista de usuário.~~

~~6. **Opções de edição limitadas:** Na função de editar, seria útil fornecer opções sobre o que o usuário deseja editar em vez de simplesmente editar todos os dados do livro em questão.~~

~~7. **Falta de tratativas para entradas de dados:** Há falta de várias tratativas para entradas de dados, o que pode resultar em comportamentos inesperados ou erros no programa.~~

No geral, estas são algumas sugestões para aprimorar o código. Parabenizo pelo trabalho realizado!

@roscibely @CarlosH6 @OtavioMartins08

**Comment by carlosabrantesdev** [comment]
Bom dia, provavelmente esses problemas foram gerados devido a um dessincronização dos códigos, pois atualizei o código ontem e meu parceiro deve ter esquecido de atualizar no github.

**Comment by carlosabrantesdev** [comment]
E a função "adicionarLivro" não é requisitada no papel do projeto, porém posso adiciona-lá (foram requisitadas 8 funções).

**Comment by JhoanDev** [comment]
Ok sem problemas, ajuste e fechei a issues! Coloque como concluída...

**Comment by JhoanDev** [comment]
Não precisa mesmo da de adicionar nao, so devolver e emprestar, acabei de verificar no pdf, desculpe pelo equivoco

**Comment by JhoanDev** [comment]
@CarlosH6

**Comment by carlosabrantesdev** [comment]
Agora existe somente a lista de usuários na main e também, a orientadora Cibely, me disse que está ok usar dois .txt.
Por este motivo vou deixar como concluido o issue, pois já estão resolvidos.
